---
- name: Test server
  hosts: test
  remote_user: root
  tasks:
    - name: Install prequisites for Docker
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: Get Docker GPG Keyrings
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg
    - name: Setup Docker Repository
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Install Docker
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: true
    - name: Start Docker
      systemd:
        name: docker
        enabled: true
        masked: no
        daemon_reload: yes
    - name: Install JDK 11
      apt:
        name: openjdk-11-jdk
